### ISSUE TITLE
native-dns server error

### ISSUE THREAD

**Issue by MasonQAQ** [brannondorsey/whonow#8]
native-dns server error:
TypeError: ans.address.padEnd is not a function
    at response.answer.forEach.ans (/usr/lib/node_modules/whonow/index.js:98:71)
    at Array.forEach (native)
    at UDPServer.server.on (/usr/lib/node_modules/whonow/index.js:66:29)
    at emitTwo (events.js:106:13)
    at UDPServer.emit (events.js:191:7)
    at UDPServer.Server.handleMessage (/usr/lib/node_modules/whonow/node_modules/native-dns/lib/server.js:68:10)
    at Socket.<anonymous> (/usr/lib/node_modules/whonow/node_modules/native-dns/lib/server.js:80:10)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:561:8)

**Comment by brannondorsey** [comment]
It looks like `ans.address` is probably undefined [here](https://github.com/brannondorsey/whonow/blob/master/index.js#L98). Do you have an example DNS query which can trigger this exception?

Ideally you could pass me a `dig` command which I could use to reproduce it. Otherwise, do you have any additional logs or context?
